### ISSUE TITLE
关于 beamer item one by one 功能

### ISSUE THREAD

**Issue by lnw143** [favourhong/Awesome-Marp#38]
Latex Beamer 中有一个很常用的功能，就是将一张页面中的几个 `item` 分页出现，以获得像 ppt 一样的效果，个人觉得这个功能十分有用，但是目前还没有找到用 Awesome Marp 实现的方法。

latex 语法：

```tex
\begin{itemize}[<+->]
  \item Item 1
  \item Item 2
  ...
  \item Item n
\end{itemize}
```

请问目前是否有办法能实现？如果不行的话，请问作者能否在未来加入这项 feature？

感谢作者的无私奉献~

**Comment by favourhong** [comment]
Markdown 的 list 语法可以使用 `- ` 或者 `* `，二者渲染出来的效果是相同的，不一样的地方在于动画效果，`- ` 渲染出来是没有动画效果的，而 `* ` 渲染出来在 HTML 打开后，可以次第呈现，有动画效果。

当然，这是基于 HTML 的展示效果，如果导出成 PDF，`* ` 也一样无法呈现出效果。

**Comment by lnw143** [comment]
thanks!
