### ISSUE TITLE
无法正确预览

### ISSUE THREAD

**Issue by ncwuguo** [favourhong/Awesome-Marp#7]
![image](https://github.com/favourhong/Awesome-Marp/assets/54211354/5732e30b-30ad-409d-93f3-cf2cb167025b)

好像没办法正确渲染，请问作者这是哪里的问题，感谢！！！

**Comment by favourhong** [comment]
直接使用 VS Code 打开 Awesome-Marp-main 文件夹，而非外层还有文件夹
