### ISSUE TITLE
<!-- _class: --> 仅支持单个属性吗

### ISSUE THREAD

**Issue by ncwuguo** [favourhong/Awesome-Marp#8]
比如，我使用`<!-- _class: navbar -->`启用了导航栏，标题分别为`*一*、*二*、**三**、*四*、*五*`
但是在第三部分又细分了两个部分，分别是3.1和3.2

我想即让上方出现导航栏，显示目前的是第三大部分，我又想启用`<!-- _class: fixedtitleB -->`以使用固定标题栏，来获得更好的展示效果

于是在这个页面我的语法是：
```
## 3.1 XXX

<!-- _header: \ *一* *二* **三** *四* *五*-->
<!-- _class: navbar -->
<!-- _class: fixedtitleB -->

面向一对多记录的数据隐私保护方法研究
```

我的理想结果图是这样的：
![image](https://github.com/favourhong/Awesome-Marp/assets/54211354/222da1b8-46f3-4f02-aade-b36725020c45)

但是结果好像是整个页面都乱了

**Comment by favourhong** [comment]
可以实现你预期的效果，具体见下图：

![image](https://github.com/favourhong/Awesome-Marp/assets/71331564/a5a8abde-7e23-472f-ae73-a5c74ca579c3)
